apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloak-operator
rules:
  - apiGroups:
      - "admissionregistration.k8s.io"
    resources:
      - validatingwebhookconfigurations
    verbs:
      - create
      - delete
  - apiGroups:
      - apps
    resourceNames:
      - keycloak-operator
    resources:
      - deployments/finalizers
    verbs:
      - update
