kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: keycloak-operator
subjects:
  - kind: ServiceAccount
    name: keycloak-operator
    # Replace this with the namespace where the operator will be deployed.
    namespace: keycloak
roleRef:
  kind: ClusterRole
  name: keycloak-operator
  apiGroup: rbac.authorization.k8s.io
